apps/appointments/urls.py
from django.conf.urls import url
from . import views

app_name="appointments"

urlpatterns = [
    url(r'^$', views.start, name='start'),
    url(r'^new$', views.new, name='new'),
    url(r'^edit/(?P<id>[0-9]+$)', views.edit, name='edit'),
    url(r'^delete/(?P<id>[0-9]+$)', views.delete, name='delete'),
    url(r'^change/(?P<id>[0-9]+$)', views.change, name='change'),
]

apps/login_registration/urls.py
from django.conf.urls import url
from . import views

app_name="login_registration"

urlpatterns = [
    url(r'^$', views.start, name='start'),
    url(r'^actions', views.actions, name='actions'),
]

main/urls.py
from django.conf.urls import url, include
#from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_registration.urls')),
    url(r'^appointments/', include('apps.appointments.urls')),
]

apps/appointments/models.py
from __future__ import unicode_literals
from ..login_registration.models import User
from django.db import models

# Create your models here.

class Appointment(models.Model):
    task = models.CharField(max_length=100)
    date = models.DateField(auto_now=False, auto_now_add=False)
    time = models.TimeField(auto_now=False, auto_now_add=False)
    user = models.ForeignKey(User, related_name="appointments")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

apps/login_registration/models.py
from __future__ import unicode_literals
from django.db import models
import re
import datetime
import bcrypt

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')

# Create your models here.

class UserManager(models.Manager):
    #Check first name
    def name_validate(self, name):
        if len(name) > 1:
            return True
        else:
            return False
    #Check email length
    def email_validate(self, email):
        if not EMAIL_REGEX.match(email):
            return False
        else:
            return True
    #Check if email already exists
    def email_exists(self, email):
        check = User.objects.filter(email = email).exists()
        if check:
            return False
        else:
            return True
    #Check password
    def password_validate(self, password):
        if len(password) > 5:
            return True
        else:
            return False
    #Check password
    def password_match(self, password, confirm_password):
        if password == confirm_password:
            return True
        else:
            return False
    #Create User
    def createUser(self, name, email, password, dob):
        user = self.create(name= name, email = email, password = bcrypt.hashpw(password.encode(), bcrypt.gensalt()), dob = dob)
        return user
    #Check entered password matches database password
    def passwordsMatchCheck(self, entered_pw, db_pw):
        if bcrypt.hashpw(entered_pw.encode(), db_pw.encode()) != db_pw:
            return False
        else:
            return True

class User(models.Model):
    name = models.TextField(max_length = 50)
    email = models.EmailField(max_length = 100)
    password = models.CharField(max_length = 100)
    dob = models.DateField(auto_now=False, auto_now_add=False)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = UserManager()

apps/appointments/views.py
from django.shortcuts import render, redirect
from .models import Appointment
from ..login_registration.models import User
import datetime
# Create your views here.

def start(request):
    appointments = Appointment.objects.all()
    context={
        'appointments': appointments,
        'today': datetime.date.today(),
        'time': datetime.datetime.now().strftime('%H:%M:%p'),
    }
    return render(request, 'appointments/start.html', context)

def new(request):
    if request.method=='POST':
        if request.POST['new'] == 'new':
            user = User.objects.get(id=request.session['user_id'])
            new = Appointment.objects.create(task=request.POST['task'], date=request.POST['date'], time=request.POST['time'], user=user)
            return redirect('appointments:start')

def edit(request, id):
    appointment = Appointment.objects.get(id=id)
    context={
        'appointment': appointment
    }
    return render(request, 'appointments/edit.html', context)

def delete(request, id):
    delete = Appointment.objects.get(id=id).delete()
    return redirect('appointments:start')

def change(request, id):
    if request.method=='POST':
        if request.POST['update'] == 'update':
            changeAppointment.objects.get(id=id).update(task=request.POST['task'])
            return redirect('appointments:start')

apps/login_registration/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User
import re
import datetime

# Create your views here.
def start(request):
    return render(request, 'login_registration/start.html')

def actions(request):
    error = False
    print 'cool beans'
    if request.method == 'POST':
        if request.POST['action'] == 'register':
            #name
            name = User.objects.name_validate(request.POST['name'])
            if not name:
                messages.add_message(request, messages.ERROR, 'Name too short!', extra_tags = 'name')
                error = True
            #email
            email = User.objects.email_validate(request.POST['email'])
            if not email:
                messages.add_message(request, messages.ERROR, 'Invalid email!', extra_tags = 'email')
                error = True
            #check if email exists
            email_exists = User.objects.email_exists(request.POST['email'])
            if not email_exists:
                messages.add_message(request, messages.ERROR, 'Email already exists!', extra_tags = 'email')
                error = True
            #password
            password = User.objects.password_validate(request.POST['password'])
            if not password:
                messages.add_message(request, messages.ERROR, 'Password too short!', extra_tags = 'password')
                error = True
            #confirm that the passwords match
            password_match = User.objects.password_match(request.POST['password'], request.POST['confirm_password'])
            if not password_match:
                messages.add_message(request, messages.ERROR, 'Passwords do not match!', extra_tags = 'match')
                error = True
            #confirm that dob is valid

            if error:
                print messages
                return redirect('/')
            else:
                new = User.objects.createUser(name = request.POST['name'], email = request.POST['email'],password = request.POST['password'], dob = request.POST['dob'])
                request.session['user_id']=new.id
                request.session['user_name']=new.name
                request.session['user_email']=new.email
                request.session['user_dob']=str(new.dob)
                return redirect('appointments:start')

        elif request.POST['action'] == 'login':
            try:
                user = User.objects.get(email = request.POST['email'])
            except Exception:
                messages.add_message(request, messages.ERROR, 'Email does not exist. Please register to login in!', extra_tags = 'deny')
                return redirect('/')

            if not User.objects.passwordsMatchCheck(request.POST['password'], user.password):
                messages.add_message(request, messages.ERROR, 'Email or password is not correct!', extra_tags = 'deny')
                return redirect('login_registration:start')
            else:
                request.session['user_id']=user.id
                request.session['user_name']=user.name
                request.session['user_email']=user.email
                request.session['user_dob']=str(user.dob)
                return redirect('appointments:start')

apps/appointments/templates/appointments/edit.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Edit</title>
    </head>
    <script>
        function myFunction() {
            document.getElementById("myDate").value = "1984-01-01";
        }
    </script>
    <body>
        <div class="header">
            <a href="{% url 'appointments:start' %}">Dashboard</a>
            <a href="{% url 'login_registration:start' %}">Logout</a>
        </div>
        <form action="{% url 'appointments:change' id=appointment.id %}" method="post">
            {% csrf_token %}
            <label for="task">Task:</label>
            <input type="text" name="task" placeholder="{{appointment.task}}">
            <label for="status">Status:</label>
            <select name="status">
                <option value="Done">Done</option>
                <option value="Pending">Pending</option>
                <option value="Missed">Missed</option>
            </select>
            <label for="date">Date:</label>
            <input type="date" name="date" value="{{appointment.date}}"  id="myDate">
            <label for="time">Time:</label>
            <input type="time" name="time" value="{{appointment.time}}">
            <button type="submit" name="update" value="update">Update</button>
        </form>
    </body>
</html>

apps/appointments/templates/appointments/start.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Start</title>
    </head>
    <script>
        function myFunction() {
            document.getElementById("myDate").value = "1984-01-01";
        }
    </script>
    <body>
        <div class="container">
            <div = "header">
                <p>Hello, {{request.session.user_name}}</p>
                <a href = "{% url 'login_registration:start' %}">Logout</a>
            </div>
            <div class="schedule">
                <p>Here are your appoints for today, {{today}}</p>
                <table>
                    <thead>
                        <th>Tasks</th>
                        <th>Time</th>
                        <th>Status</th>
                        <th>Action</th>
                    </thead>
                    <tbody>
                    {% if appointments %}
                        {% for appointment in appointments %}
                            {% if appointment.user.id == request.session.user_id %}
                                {% if appointment.date == today %}
                                    <tr>
                                        <td>{{appointment.task}}</td>
                                        <td>{{appointment.time}}</td>
                                        {% if appointment.time < time %}
                                            <td>Done</td>
                                        {% elif appointment.time > time %}
                                            <td>Pending</td>
                                        {% endif %}
                                        <td>Pending</ts>
                                        <td><a href="{% url 'appointments:edit' id=appointment.id %}">Edit</a> <a href="{% url 'appointments:delete' id=appointment.id %}">Delete</a></td>
                                    </tr>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
            <div class="future">
                <h3>Your Other Appointments</h3>
                <table>
                    <thead>
                        <th>Tasks</th>
                        <th>Date</th>
                        <th>Time</th>
                    </thead>
                    <tbody>
                    {% if appointments %}
                        {% for appointment in appointments %}
                            {% if appointment.user.id == request.session.user_id %}
                                {% if appointment.date != today %}
                                <tr>
                                    <td>{{appointment.task}}</td>
                                    <td>{{appointment.date}}</td>
                                    <td>{{appointment.time}}</td>
                                </tr>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
            <div class="new">
                <h3>Add Appointment</h3>
                <form action="{% url 'appointments:new' %}" method="post">
                    {% csrf_token %}
                    <label for="date">Date</label>
                    <input type="date" name="date" id="myDate">
                    <label for="time">Time</label>
                    <input type="time" name="time">
                    <label for="task">Task</label>
                    <input type="text" name="task">
                    <button type="submit" name="new" value="new">Add</button>
                </form>
            </div>
        </div>
    </body>
</html>

apps/login_registration/templates/login_registration/start.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'login_registration/css/start_style.css' %}">
    </head>
    <script>
        function myFunction() {
            document.getElementById("myDate").value = "1984-01-01";
        }
    </script>
    <body>
        <div class = "container center">
            <form class="new_user" action="/actions" method="post">
                {% csrf_token %}
                {% if messages %}
                    {% for message in messages %}
                        {% if 'fname' in message.tags %}
                            <p class = "red">{{message}}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <input type="text" name="name" placeholder="Name">
                {% if messages %}
                    {% for message in messages %}
                        {% if 'email' in message.tags %}
                            <p class = "red">{{message}}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <input type="email" name="email" placeholder="Email">
                {% if messages %}
                    {% for message in messages %}
                        {% if 'password' in message.tags %}
                            <p class = "red">{{message}}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <input type="text" name="password" placeholder="Password">
                {% if messages %}
                    {% for message in messages %}
                        {% if 'match' in message.tags %}
                            <p class = "red">{{message}}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <input type="text" name="confirm_password" placeholder="Confirm Password">
                {% if messages %}
                    {% for message in messages %}
                        {% if 'dob' in message.tags %}
                            <p class = "red">{{message}}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <input type="date" name="dob" id="myDate">
                <button type="submit" name="action" value="register">Register</button>
            </form>
            <form class="login" action="/actions" method="post">
                {% csrf_token %}
                {% if messages %}
                    {% for message in messages %}
                        {% if 'deny' in message.tags %}
                            <p class = "red">{{message}}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <input type="email" name="email" placeholder="Email">
                <input type="text" name="password" placeholder="Password">
                <button type="submit" name="action" value="login">Login</button>
            </form>
        </div>
    </body>
</html>